@ECHO OFF

REM Ú‘±ŠÂ‹«
SET HOST=localhost
SET PORT=5432
SET DB_NAME=TSSTS_MAIN
SET CONN_USER=TSSTS_MAIN_USER
SET CONN_PASS=TSSTS_MAIN_USER

ECHO Ú‘±ŠÂ‹«‚ÌŠm”F
ECHO HOST=%HOST%
ECHO PORT=%PORT%
ECHO DB_NAME=%DB_NAME%
ECHO CONN_USER=%CONN_USER%
ECHO CONN_PASS=%CONN_PASS%

ECHO.

PAUSE
