@ECHO OFF

REM 接続環境
SET HOST=localhost
SET PORT=5432
SET DB_ADMIN_NAME=postgres
SET CONN_ADMIN_USER=postgres
SET CONN_ADMIN_PASS=postgres
SET DB_NAME=TSSTS_MAIN
SET CONN_USER=TSSTS_MAIN_USER
SET CONN_PASS=TSSTS_MAIN_USER
SET SQL_BASE_PASS=..\..\
SET SQL_DDL_DB_PASS=%SQL_BASE_PASS%\CB020_DDL\DB010_データベース
SET SQL_DDL_TBL_PASS=%SQL_BASE_PASS%\CB020_DDL\DB020_テーブル
SET SQL_DML_PASS=%SQL_BASE_PASS%\CB030_データ\DA020_DML

ECHO 接続環境の確認
ECHO HOST=%HOST%
ECHO PORT=%PORT%
ECHO DB_ADMIN_NAME=%DB_ADMIN_NAME%
ECHO CONN_ADMIN_USER=%CONN_ADMIN_USER%
ECHO CONN_ADMIN_PASS=%CONN_ADMIN_PASS%
ECHO DB_NAME=%DB_NAME%
ECHO CONN_USER=%CONN_USER%
ECHO CONN_PASS=%CONN_PASS%
ECHO SQL_DDL_DB_PASS=%SQL_DDL_DB_PASS%
ECHO SQL_DDL_TBL_PASS=%SQL_DDL_TBL_PASS%
ECHO SQL_DML_PASS=%SQL_DML_PASS%

ECHO.

PAUSE
